// javascript execution context

// When we give code to compiler, it returns Global Executive context i.e. {this}

// Javascript is a single threaded programming language

// There are three EC
// 1. Global Execution context
// 2. Function Execution Context
// 3. Eval Exectution Context

// {Code here} --> memory creation phase
//             --> Execution phase

// Everytime a function runs it gets through the same loop of memory phase and execution phase

// CALLSTACK

// Call stack handles all the functions and methods which works on a mechanism called LIFO(Last in first out)

// But at first it handles global state and after that it handles rest of the functions
// We can see callstack in source tab in browsers